spec:
  template:
    metadata:
      labels:
      app: yasumi-puzzler
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 128Mi
            limits:
              cpu: "1.0"
              memory: 512Mi
